const questionsReact = [
  {
    id: 1,
    level: '초급',
    title: 'react',
    body: '우리 회사에 지원한 동기를 말씀해주실 수 있을까요?',
  },
  {
    id: 2,
    level: '초급',
    title: 'react',
    body: '개발자가 되기로 한 이유에 대해 말씀해주실 수 있을까요?',
  },
  {
    id: 3,
    level: '초급',
    title: 'react',
    body: '즐겨 보는 테크 유튜버나 뉴스레터가 있다면 알려주실 수 있을까요?',
  },
  {
    id: 4,
    level: '초급',
    title: 'react',
    body: '최근에 본 기술 아티클에 대해 설명해주실 수 있을까요?',
  },
  {
    id: 5,
    level: '초급',
    title: 'react',
    body: '개발자로서 본인의 장단점과 근거가 되는 경험을 말씀해주실 수 있을까요?(협업 능력 제외)',
  },
  {
    id: 6,
    level: '초급',
    title: 'react',
    body: '앞으로 3개월, 6개월, 1년 동안 어떤 것을 공부할 계획인지, 그리고 그러한 계획을 세운 이유는 무엇인지 알려주실 수 있을까요?',
  },
  {
    id: 7,
    level: '초급',
    title: 'react',
    body: '가장 인상 깊게 읽었던 책과 그 이유에 대해 알려주실 수 있을까요?',
  },
  {
    id: 8,
    level: '초급',
    title: 'react',
    body: '삶에서 중요하게 생각하는 가치가 있다면 무엇인가요?',
  },
  {
    id: 9,
    level: '초급',
    title: 'react',
    body: '즐겁고 행복했던 경험을 하나 이야기해주실 수 있을까요?',
  },
  {
    id: 10,
    level: '초급',
    title: 'react',
    body: '힘들고 쉽지 않았지만 극복한 경험을 하나 이야기해주실 수 있을까요?',
  },
  {
    id: 11,
    level: '초급',
    title: 'react',
    body: '시간복잡도와 공간복잡도가 무엇인지 설명해주실 수 있을까요?',
  },
  {
    id: 12,
    level: '초급',
    title: 'react',
    body: '재미있게 공부한 알고리즘이 있다면 설명해주실 수 있을까요?',
  },
  {
    id: 13,
    level: '초급',
    title: 'react',
    body: '스택, 큐에 대해 설명해주실 수 있을까요?',
  },
  {
    id: 14,
    level: '초급',
    title: 'react',
    body: '배열, 링크드리스트를 비교하여 설명해주실 수 있을까요?',
  },
  {
    id: 15,
    level: '초급',
    title: 'react',
    body: 'CORS란 무엇이고 어떻게 허용할 수 있나요?',
  },
  {
    id: 16,
    level: '초급',
    title: 'react',
    body: '사용자 패스워드를 전송하고 보관하는 방법을 설명해주실 수 있을까요?',
  },
  {
    id: 17,
    level: '초급',
    title: 'react',
    body: 'var, let, const 에 대해 설명해주실 수 있을까요?',
  },
  {
    id: 18,
    level: '초급',
    title: 'react',
    body: 'Promise란 무엇인지 설명해주실 수 있을까요?',
  },
  {
    id: 19,
    level: '초급',
    title: 'react',
    body: 'Hoisting이란 무엇인지 설명해주실 수 있을까요?',
  },
  {
    id: 20,
    level: '초급',
    title: 'react',
    body: 'async/await 이란 무엇인지 설명해주실 수 있을까요?',
  },
  {
    id: 21,
    level: '초급',
    title: 'react',
    body: 'Arrow Function 이란 무엇인지 설명해주실 수 있을까요?',
  },
  {
    id: 22,
    level: '초급',
    title: 'react',
    body: '‘==’와 ‘===’ 연산자의 차이는 무엇인지 설명해주실 수 있을까요?',
  },
  {
    id: 23,
    level: '초급',
    title: 'react',
    body: 'Virtual DOM이란 무엇이고 Real DOM과의 차이는 무엇인가요?',
  },
  {
    id: 24,
    level: '초급',
    title: 'react',
    body: 'useRef 에 대해 아는 만큼 설명해주실 수 있을까요?',
  },
  {
    id: 25,
    level: '초급',
    title: 'react',
    body: '리액트 컴포넌트의 라이프사이클에 대해 설명해주실 수 있을까요?',
  },
  {
    id: 26,
    level: '초급',
    title: 'react',
    body: 'JSX란 무엇인가요?',
  },
  {
    id: 27,
    level: '초급',
    title: 'react',
    body: '세션과 쿠키를 비교하여 설명해주실 수 있을까요?',
  },
  {
    id: 28,
    level: '초급',
    title: 'react',
    body: '브라우저에서 이용할 수 있는 스토리지는 무엇이 있는지 설명해주실 수 있을까요?',
  },
  {
    id: 29,
    level: '초급',
    title: 'react',
    body: 'ContextAPI 란 무엇인가요?',
  },
  {
    id: 30,
    level: '중급',
    title: 'react',
    body: '포트폴리오에서 시간복잡도를 낮춘 사례가 있다면 설명해주실 수 있을까요?',
  },
  {
    id: 31,
    level: '중급',
    title: 'react',
    body: '이분탐색이 무엇이고 시간복잡도는 어떻게 되며 그 이유는 무엇인가요?',
  },
  {
    id: 32,
    level: '중급',
    title: 'react',
    body: '트리, 그래프를 비교하여 설명해주실 수 있을까요?',
  },
  {
    id: 33,
    level: '중급',
    title: 'react',
    body: 'HTTP에 비해 HTTPS가 더 안전한 원리를 설명해주실 수 있을까요?',
  },
  {
    id: 34,
    level: '중급',
    title: 'react',
    body: 'TCP 3 way handshake란 무엇인지 설명해주실 수 있을까요?',
  },
  {
    id: 35,
    level: '중급',
    title: 'react',
    body: 'TCP 와 UDP 를 비교하여 설명해주실 수 있을까요?',
  },
  {
    id: 36,
    level: '중급',
    title: 'react',
    body: 'Base64 인코딩이란 무엇인가요?',
  },
  {
    id: 37,
    level: '중급',
    title: 'react',
    body: '프로세스와 스레드를 비교하여 설명해주실 수 있을까요?',
  },
  {
    id: 38,
    level: '중급',
    title: 'react',
    body: '깊은 복사와 얕은 복사의 차이는 무엇이고 JS에서 각각을 구현하는 방법은 어떻게 되는지 설명해주실 수 있을까요?',
  },
  {
    id: 39,
    level: '중급',
    title: 'react',
    body: 'JS의 passed by value 와 passed by reference 에 대해 아는 만큼 설명해주실 수 있을까요?',
  },
  {
    id: 40,
    level: '중급',
    title: 'react',
    body: '고차 함수란 무엇인지 설명해주실 수 있을까요?',
  },
  {
    id: 41,
    level: '중급',
    title: 'react',
    body: '다음 함수의 결과의 예측과 근거를 설명해주실 수 있을까요?',
  },
  {
    id: 42,
    level: '중급',
    title: 'react',
    body: 'VanillaJS와 비교하여 리액트를 사용하는 이유에 대해 설명해주실 수 있을까요?',
  },
  {
    id: 43,
    level: '중급',
    title: 'react',
    body: '상태의 불변성이 중요한 이유가 무엇인가요?',
  },
  {
    id: 44,
    level: '중급',
    title: 'react',
    body: 'Lazy loading과 Code splitting에 대해 아는 만큼 설명해주실 수 있을까요?',
  },
  {
    id: 45,
    level: '중급',
    title: 'react',
    body: 'https://naver.com 을 주소창에 입력했을 때 일어나는 과정에 대해 아는 만큼 설명해주실 수 있을까요?',
  },
  {
    id: 46,
    level: '중급',
    title: 'react',
    body: 'Server Side Rendering, Client Side Rendering, Static Site Generation 의 장단점을 설명해주실 수 있을까요?',
  },
  {
    id: 47,
    level: '중급',
    title: 'react',
    body: 'Event bubbling 과 capturing 을 비교하여 설명해주실 수 있을까요?',
  },
  {
    id: 48,
    level: '고급',
    title: 'react',
    body: '상태관리의 대표적인 도구 하나와 그것의 원리에 대해 구체적으로 설명해주실 수 있을까요? 예를 들어 리덕스라면 리덕스가 무엇이고 어떻게 활용이 되는지, 어떤 흐름으로 데이터가 들어왔다가 나가는지, 데이터 흐름은 양방향인지 단방향인지, 어떤 함수가 데이터를 가져오게 해주는지 등을 언급해주시면 좋습니다.',
  },
  {
    id: 49,
    level: '고급',
    title: 'react',
    body: '브라우저 렌더링 과정에 대해 아는 만큼 설명해주실 수 있을까요? 예를 들어 화면에서 DOM이 어떻게 결정되고, CSS는 어떻게 입혀지는지 등을 언급해주시면 좋습니다.',
  },
  {
    id: 50,
    level: '고급',
    title: 'react',
    body: 'Web Vital을 개선할 수 있는 방안에 대해 설명해주실 수 있을까요? 예를 들어 LCP, CLS, FID 각각의 개념, 진단법, 각 지표 개선에 효과적인 조치 방안을 언급해주시면 좋습니다.',
  },
];

export default function handler(req, res) {
  res.status(200).json(questionsReact);
}
